#-------------------------------
# Site Settings
title: boxblinkracer
logo: # You can add own logo. For example '/images/logo.png'.
description: Hi my name is Christian
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
  #  - title: 'Dev Projects'
 #     url: '/projects/'
    - title: 'Talks'
      url: '/talks/'
   # - title: 'Courses'
   #   url: '/courses/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'Contact'
      url: '/contact/'

#-------------------------------
# Author Settings
author:
  author__name: Christian Dangl
  author__bio: I develop things for mobile, web and desktop, and I love to teach people about Software Architecture and quality.
  author__avatar: '/images/01.jpg'

social:
  - { icon: "ion-logo-twitter", link: "https://twitter.com/boxblinkracer" }
  - { icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/cdangl/" }
  - { icon: "ion-logo-github", link: "https://github.com/boxblinkracer" }

# Example of adding a new link to the footer - {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Hero Settings
hero:
  hero__title: I'm Christian and I develop software and products
  hero__description: I develop things for mobile, web and desktop, and I love to teach people about Software Architecture and quality.<br /><br /><ul><li>Working at <span class="text-highlight">dasistweb GmbH</span> for e-Commerce stuff</li><li>Owner of <span class="text-highlight">Live Score GmbH</span> for scoreboard graphics stuff</li></ul>I like Shopware, writing articles, giving talks, video production and everything else :)
  hero__image: '/images/01.jpg'


#-------------------------------
codestyle__settings:
  codestyle__title: about my coding style?!....
  codestyle__description: Separation of concerns mixed with well thought DI on immutable objects that fail fast and are being used through their interfaces for real integration or fake integration in lots of unit and integration tests!


#-------------------------------
# Projects Settings
projects__settings:
  projects__title: Things I do
  projects__description:


#-------------------------------
# Testimonials Section
testimonial__title: What people say
testimonial__description:

#testimonial__items:
#  - name: "Aspen Carder"
#    image: "/images/client-1.jpg"
#    designation: "Lettering Artist"
#    link: "https://twitter.com/"
#    content: "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"
#
#  - name: "Lydia Siphron"
#    image: "/images/client-2.jpg"
#    designation: "Designer"
#    link: "https://facebook.com/"
#    content: "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"
#
#  - name: "Craig Vaccaro"
#    image: "/images/client-3.jpg"
#    designation: "Web developer"
#    link: "https://twitter.com/"
#    content: "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"
#
#  - name: "Anika Calzoni"
#    image: "/images/client-4.jpg"
#    designation: "Lettering Artist"
#    link: "https://facebook.com/"
#    content: "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"
#
#  - name: "Marcus Botosh"
#    image: "/images/client-5.jpg"
#    designation: "Full Stack Designer"
#    link: "https://twitter.com/"
#    content: "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"


#-------------------------------
# Blog Section
blog__settings:
  blog__title: Recent Posts
  blog__description:


#-------------------------------
# Gallery Footer Settings
gallery:
  gallery__images:
    - alt: 'Rest'
      url: '/images/gallery-1.jpg'
    - alt: 'Lifestyle'
      url: '/images/gallery-2.jpg'
    - alt: 'Hobby'
      url: '/images/gallery-3.jpg'
    - alt: 'Notes'
      url: '/images/gallery-4.jpg'


#-------------------------------
# Footer Navigation Settings
footer_menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
   # - title: 'Dev Projects'
   #   url: '/projects/'
   # - title: 'Talks'
   #   url: '/talks/'
   # - title: 'Courses'
   #   url: '/courses/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'Contact'
      url: '/contact/'

#-------------------------------
# Contact Settings
contact:
  email: xlevryww
  description: Questions? Just get in touch with me.

# NOTE
# Hilton theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier:  # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: G-04HM4XF4VK